title : Bush 631 - Spring 2023
logo: /assets/hex.png
author :
  name : Rotem Dvir
  email : rdvir@tamu.edu
  github : rotemdvir
  twitter : nil
  feedburner : nil

markdown: kramdown
google_analytics:

theme: jekyll-theme-minimal
